%% ----------------- TELEMETRY READING -----------------

% Reading data file 
telemetry_data = readtable("CS4.csv");

% Extracting relevant data streams
session_time = telemetry_data.SessionTime;
lap = telemetry_data.Lap;
lap_tracking = telemetry_data.LapDistance_m;

speed = telemetry_data.Speed_kmh;
throttle_pos = telemetry_data.Throttle;
brake_pos = telemetry_data.Brake;
steering_angle = telemetry_data.Steer;

gear = telemetry_data.Gear;
engine_RPM = telemetry_data.EngineRPM;
engine_temp = telemetry_data.EngineTemperature;
drs_activated = telemetry_data.DRS;

FL_Brake_Temp = telemetry_data.BrakeTemp_FL;
FR_Brake_Temp = telemetry_data.BrakeTemp_FR;
RL_Brake_Temp = telemetry_data.BrakeTemp_RL;
RR_Brake_Temp = telemetry_data.BrakeTemp_RR;

FL_Tyre_Surf_Temp = telemetry_data.TyreSurfTemp_FL;
FR_Tyre_Surf_Temp = telemetry_data.TyreSurfTemp_FR;
RL_Tyre_Surf_Temp = telemetry_data.TyreSurfTemp_RL;
RR_Tyre_Surf_Temp = telemetry_data.TyreSurfTemp_RR;

FL_Tyre_Inner_Temp = telemetry_data.TyreInnerTemp_FL;
FR_Tyre_Inner_Temp = telemetry_data.TyreInnerTemp_FR;
RL_Tyre_Inner_Temp = telemetry_data.TyreInnerTemp_RL;
RR_Tyre_Inner_Temp = telemetry_data.TyreInnerTemp_RR;

FL_Tyre_Pressure = telemetry_data.TyrePressure_FL;
FR_Tyre_Pressure = telemetry_data.TyrePressure_FR;
RL_Tyre_Pressure = telemetry_data.TyrePressure_RL;
RR_Tyre_Pressure = telemetry_data.TyrePressure_RR;

%% ----------------- CALCULATING LAP TIMES -----------------

lap_numbers = unique(lap);   
lap_numbers_len = numel(lap_numbers);
lap_times = zeros(lap_numbers_len, 1);

for k = 1:lap_numbers_len
    L = lap_numbers(k);
    idx_start = find(lap == L, 1, 'first');
    idx_finish = find(lap == L, 1, 'last');
    lap_time = session_time(idx_finish) - session_time(idx_start);
    lap_times(k) = lap_time;
end

%% ----------------- DETERMINING FASTEST LAP -----------------
fastest_lap_time = min(lap_times);
idx_fastest_lap_time = find(lap_times == fastest_lap_time, 1);
fastest_lap_num = lap_numbers(idx_fastest_lap_time);

%% ----------------- ORGANIZING HOT LAP DATA -----------------
mask = lap == fastest_lap_num;

HL_lap_distance = lap_tracking(mask);
HL_speed  = speed(mask);  
HL_throttle_pos = throttle_pos(mask);
HL_brake_pos = brake_pos(mask);
HL_steering_angle = steering_angle(mask);
HL_gear = gear(mask);
HL_engine_RPM = engine_RPM(mask);
HL_engine_temp = engine_temp(mask);
HL_drs_activated = drs_activated(mask);
HL_FL_Brake_Temp = FL_Brake_Temp(mask);
HL_FR_Brake_Temp = FR_Brake_Temp(mask);
HL_RL_Brake_Temp = RL_Brake_Temp(mask);
HL_RR_Brake_Temp = RR_Brake_Temp(mask);
HL_FL_Tyre_Surf_Temp = FL_Tyre_Surf_Temp(mask);
HL_FR_Tyre_Surf_Temp = FR_Tyre_Surf_Temp(mask);
HL_RL_Tyre_Surf_Temp = RL_Tyre_Surf_Temp(mask);
HL_RR_Tyre_Surf_Temp = RR_Tyre_Surf_Temp(mask);
HL_FL_Tyre_Inner_Temp = FL_Tyre_Inner_Temp(mask);
HL_FR_Tyre_Inner_Temp = FR_Tyre_Inner_Temp(mask);
HL_RL_Tyre_Inner_Temp = RL_Tyre_Inner_Temp(mask);
HL_RR_Tyre_Inner_Temp = RR_Tyre_Inner_Temp(mask);
HL_FL_Tyre_Pressure = FL_Tyre_Pressure(mask);
HL_FR_Tyre_Pressure = FR_Tyre_Pressure(mask);
HL_RL_Tyre_Pressure = RL_Tyre_Pressure(mask);
HL_RR_Tyre_Pressure = RR_Tyre_Pressure(mask);

%% ----------------- PLOTTING HOT LAP SPEED TRACE -----------------

minutes = floor(fastest_lap_time / 60);
seconds = mod(fastest_lap_time, 60);
lap_time_str = sprintf('Lap Time: %d:%05.2f', minutes, seconds);

figure;
set(gcf, 'Position', [100 100 800 600]);

subplot(2,1,1);
yyaxis left
h1 = plot(HL_lap_distance, HL_speed, '-b', 'LineWidth', 1.5);
ylabel('Speed (km/h)')
ax = gca; ax.YColor = 'k';

yyaxis right
h2 = plot(HL_lap_distance, HL_engine_RPM, '-r', 'LineWidth', 1.5);
ylabel('Engine RPM')
ax = gca; ax.YColor = 'k';

xlabel('Lap Distance (m)')
title(sprintf('Lap %d: Speed & RPM vs Lap Distance', fastest_lap_num))
legend([h1 h2], {'Speed', 'Engine RPM'}, 'Location', 'best')
xlim([min(HL_lap_distance), max(HL_lap_distance)])
grid on

% Top-right annotation
annotation('textbox', [0.70, 0.91, 0.28, 0.05], ...
    'String', lap_time_str, ...
    'FitBoxToText', 'on', ...
    'BackgroundColor', [1, 0.85, 0.4], ...
    'EdgeColor', [0.85, 0.33, 0.1], ...
    'Color', [0, 0, 0.5], ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'center');

subplot(2,1,2);
hold on
p1 = plot(HL_lap_distance, HL_throttle_pos, '-g', 'LineWidth', 1.2);
p2 = plot(HL_lap_distance, HL_brake_pos, '-r', 'LineWidth', 1.2);
p3 = plot(HL_lap_distance, HL_steering_angle, '-c', 'LineWidth', 1.2);
p4 = plot(HL_lap_distance, HL_gear, '-m', 'LineWidth', 1.2);
hold off

xlabel('Lap Distance (m)')
ylabel('Value')
title(sprintf('Lap %d: Controls vs Lap Distance', fastest_lap_num))
legend([p1 p2 p3 p4], ...
    {'Throttle (%)', 'Brake (%)', 'Steering Angle (°)', 'Gear'}, ...
    'Location','best')
xlim([min(HL_lap_distance), max(HL_lap_distance)])
grid on

%% ----------------- EXPORTING HOT LAP DATA -----------------

origFilename = "CS4.csv";           
[folder, baseName, ext] = fileparts(origFilename);
newBaseName = baseName + "_hotlap";
newFilename = fullfile(folder, newBaseName + ext);

T = table( ...
    HL_lap_distance(:), ...
    HL_speed(:), ...
    HL_throttle_pos(:), ...
    HL_brake_pos(:), ...
    HL_steering_angle(:), ...
    HL_gear(:), ...
    HL_engine_RPM(:), ...
    HL_engine_temp(:), ...
    HL_drs_activated(:), ...
    HL_FL_Brake_Temp(:), ...
    HL_FR_Brake_Temp(:), ...
    HL_RL_Brake_Temp(:), ...
    HL_RR_Brake_Temp(:), ...
    HL_FL_Tyre_Surf_Temp(:), ...
    HL_FR_Tyre_Surf_Temp(:), ...
    HL_RL_Tyre_Surf_Temp(:), ...
    HL_RR_Tyre_Surf_Temp(:), ...
    HL_FL_Tyre_Inner_Temp(:), ...
    HL_FR_Tyre_Inner_Temp(:), ...
    HL_RL_Tyre_Inner_Temp(:), ...
    HL_RR_Tyre_Inner_Temp(:), ...
    HL_FL_Tyre_Pressure(:), ...
    HL_FR_Tyre_Pressure(:), ...
    HL_RL_Tyre_Pressure(:), ...
    HL_RR_Tyre_Pressure(:), ...
    'VariableNames', { ...
        'LapDistance_m', ...
        'Speed_km_h', ...
        'Throttle_pct', ...
        'Brake_pct', ...
        'Steering_deg', ...
        'Gear', ...
        'Engine_RPM', ...
        'EngineTemp_C', ...
        'DRS_Active', ...
        'BrakeTemp_FL_C', ...
        'BrakeTemp_FR_C', ...
        'BrakeTemp_RL_C', ...
        'BrakeTemp_RR_C', ...
        'TyreSurfTemp_FL_C', ...
        'TyreSurfTemp_FR_C', ...
        'TyreSurfTemp_RL_C', ...
        'TyreSurfTemp_RR_C', ...
        'TyreInnerTemp_FL_C', ...
        'TyreInnerTemp_FR_C', ...
        'TyreInnerTemp_RL_C', ...
        'TyreInnerTemp_RR_C', ...
        'TyrePressure_FL_PSI', ...
        'TyrePressure_FR_PSI', ...
        'TyrePressure_RL_PSI', ...
        'TyrePressure_RR_PSI' ...
    } ...
);

writetable(T, newFilename);
fprintf('Hot-lap data written to: %s\n', newFilename);
